# -*- coding: utf-8 -*-
"""clean_inventory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9V3H3V1bMIY1wU7RFB78sSDrQXQgpYk
"""

import pandas as pd

df = pd.read_csv('/content/perishable_goods_management.csv')

print(df.shape)

print(df.info())

df.isnull().sum()

#check if there duplicate  value
print(df.duplicated().sum())

#check  the data type of columns

df.dtypes

df.head()

df.head()

df['transaction_date'] =pd.to_datetime(df['transaction_date'])
df['expiration_date'] = pd.to_datetime(df['expiration_date'])

df.info()

# The price cannot be negative.
print((df['base_price'] < 0).sum())

# The sales figure cannot be negative.
print((
        df['units_sold'] < 0).sum())

# The discount cannot exceed 100.
print((df['discount_pct'] > 100).sum())

text_columns = [
    'product_name',
    'category',
    'region',
    'quality_grade'
]

for col in text_columns :
    df[col] = df[col].str.strip()

df['category'].unique()

df['quality_grade'].unique()

df['region'].unique()

df['product_name'].unique()

df['base_price'].describe()

df['storage_temp'].describe()

df.groupby('category')['base_price'].max()

df['revenue'].describe()
df.groupby('category')['revenue'].max()

df['units_sold'].describe()
df.groupby('category')['units_sold'].max()

df.head()

df.dropna(inplace=True)

df.isnull().sum()

print(df.info())

print(df.shape)

df.to_csv('perishable_goods_clean.csv', index=False)