# -*- coding: utf-8 -*-
"""clean_sensors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RF4pyGHck8bDsRGHWG66aoiIT6zKLYTv
"""

import pandas as pd
df = pd.read_csv("smart_manufacturing_data.csv")

print(df.shape)
print(df.info())

print(df.isnull().sum())

print(df.duplicated().sum())
print(df.duplicated(subset=["timestamp", "machine_id"]).sum())

print(df["machine_status"].unique())
print(df["anomaly_flag"].unique())
print(df["maintenance_required"].unique())
print(df["failure_type"].unique())

print(pd.to_datetime(df["timestamp"], errors="coerce").isnull().sum())

for col in ["temperature", "vibration", "humidity", "pressure", "energy_consumption"]:
    print(col, "negative:", (df[col] < 0).sum())

print("humidity out of 0-100:", ((df["humidity"] < 0) | (df["humidity"] > 100)).sum())
print("downtime_risk out of 0-1:", ((df["downtime_risk"] < 0) | (df["downtime_risk"] > 1)).sum())

df["timestamp"] = pd.to_datetime(df["timestamp"])

df["failure_type"] = df["failure_type"].astype(str).str.strip()

#Negative_Oscillation_Correction (physically illogical)
df["vibration"] = df["vibration"].abs()

df = df.drop_duplicates()

#Sort by machine ID, then time
df = df.sort_values(["machine_id", "timestamp"]).reset_index(drop=True)

print(df.isnull().sum())
print(df.duplicated().sum())
print("negative vibration:", (df["vibration"] < 0).sum())

# vibration should always be >= 0 (it's a magnitude, not a direction).
# Negative values here are sensor/data errors, so we take abs() to fix the sign
# while keeping the row (only 37 out of 100,000 affected).
print("min vibration:", df["vibration"].min())
print("negative vibration count:", (df["vibration"] < 0).sum())

df.to_csv("sensors_clean.csv", index=False)