# -*- coding: utf-8 -*-
"""clean_sales.normalized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMIoYDVYGKZAHPfU8xY4pRsita0eiUHK
"""

import pandas as pd
df = pd.read_csv("/content/sales_normalized.csv")

print(df.shape)
print(df.info())

#check if there null value
print(df.isnull().sum())

#check if there duplicate  value
print(df.duplicated().sum())

for col in ["Status", "Type", "Category", "Location", "Machine"]:
    print(col, "->", df[col].unique())

print("rprice <=0:", (df["RPrice"] <= 0).sum())
print("mprice <=0:", (df["MPrice"] <= 0).sum())
print("rqty <=0:", (df["RQty"] <= 0).sum())

print(pd.to_datetime(df["TransDate"], errors="coerce").isnull().sum())
print(pd.to_datetime(df["Prcd Date"], errors="coerce").isnull().sum())

#StandardizingColumnNames
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df["transdate"] = pd.to_datetime(df["transdate"])
df["prcd_date"] = pd.to_datetime(df["prcd_date"])

df["product"] = df["product"].fillna("Unknown")
df["category"] = df["category"].fillna("Unknown")
df["mprice"] = df["mprice"].fillna(df["rprice"])

for col in ["status", "type", "category", "location", "machine"]:
    df[col] = df[col].astype(str).str.strip()

df = df.drop_duplicates()

print(df.isnull().sum())
print(df.duplicated().sum())

df.to_csv("sales_clean_normalized.csv", index=False)