# -*- coding: utf-8 -*-
"""Weather API_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yS1Bgz6HTOV6OGGs9uKA0090AMSrksJ
"""

import pandas as pd
df = pd.read_csv("/content/weather_raw_20260917T084746.csv")
print("Raw shape:", df.shape)

#Convert the time column to datetime
df["time"] = pd.to_datetime(df["time"])

#StandardizingColumnNames
df = df.rename(columns={
    "temperature_2m": "temperature",
    "relative_humidity_2m": "humidity",
    "weathercode": "weather_code",
})

print(df.isnull().sum())
print(df.duplicated().sum())
print(df.duplicated(subset=["time", "location_name"]).sum())

print("temp range:", df["temperature"].min(), df["temperature"].max())
print("humidity out of 0-100:", ((df["humidity"] < 0) | (df["humidity"] > 100)).sum())
print("negative precipitation:", (df["precipitation"] < 0).sum())

df["date"] = df["time"].dt.date
df["time_of_day"] = df["time"].dt.time

df = df.drop_duplicates()

print(df.isnull().sum())
print(df.duplicated().sum())
print(df.shape)

print(df[["time", "date", "time_of_day"]].head())
print(df.dtypes)
print(df.isnull().sum())
print(df.duplicated().sum())
print(df.shape)

df.to_csv("weather_clean_2024(final).csv", index=False)